Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 627, in <module>
    main()
  File "/usr/local/lib/python3.10/site.py", line 614, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/lib/python3.10/site.py", line 397, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 236, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 195, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/usr/local/lib/python3.10/contextlib.py", line 5, in <module>
    from collections import deque
  File "/usr/local/lib/python3.10/collections/__init__.py", line 36, in <module>
    from operator import eq as _eq
KeyboardInterrupt
